version: '3.8'
services:
    webserver:
        image: 'nginx:alpine'
        volumes:
            - '.:/application'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8008:80'

    php-fpm:
        build: ./.docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
